[tox]
envlist = basepython

[testenv]
setenv   =
    PYTHONPATH = {env:PYTHONPATH}{:}{toxinidir}/src
    MYPY_CACHE_DIR = {toxinidir}/.mypy_cache
deps =
    mypy
    ruff
    pytest
    types-requests
commands =
    pytest -vv
    mypy -p changenotifier
    ruff check --select I --select C src/changenotifier/
