[tox]
envlist = basepython

[testenv]
setenv   =
    PYTHONPATH = {env:PYTHONPATH}{:}{toxinidir}
    MYPY_CACHE_DIR = {toxinidir}/.mypy_cache
deps =
    mypy
    ruff
commands =
    mypy -p changenotifier
    ruff check --select I --select C src/changenotifier/
