name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

jobs:
  build-and-test-on-fedora:
    name: Build and test on Fedora
    runs-on: ubuntu-24.04
    container: ghcr.io/rudd-o/github-runners/fedora:latest
    steps:
       - run: dnf install -y make
         name: Install make
       - uses: actions/checkout@v6
         name: Check out code
       - run: make deps-fedora
         name: install Fedora dependencies
       - run: make rpm
         name: Create RPM (also runs tests)
  # build_wheels:
  #   name: Build wheels on ${{ matrix.os }} (${{ matrix.arch }}) for ${{ matrix.cp }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-22.04, windows-2022, macos-15-intel]
  #       arch: [auto64]
  #       cp: ["cp3{10,11,12,13,14,14t}"]
  #       include:
  #         - os: macos-14
  #           arch: arm64
  #           cp: "cp3{10,11,12,13,14,14t}"
  #         - os: ubuntu-22.04-arm
  #           arch: aarch64
  #           cp: "cp3{10,11,12,13,14,14t}"
  #         - os: windows-11-arm
  #           arch: ARM64
  #           cp: "cp3{11,12,13,14,14t}"
    # 
    # steps:
    #   - uses: actions/checkout@v6
    #     with:
    #       submodules: true
    # 
    #   - name: Build wheels
    #     uses: pypa/cibuildwheel@v3.4.1
    #     env:
    #       CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
    #       CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
    #       CIBW_BUILD: "${{ matrix.cp }}-*"
    #       CIBW_SKIP: "*musllinux*"
    #       CIBW_ARCHS: ${{ matrix.arch }}
    #       CIBW_ENVIRONMENT_MACOS: TARGET_ARCH=${{ matrix.arch }} MACOSX_DEPLOYMENT_TARGET=11.0
    #       CIBW_BEFORE_ALL: bash scripts/build_${{ runner.os }}.sh
    #       CIBW_BEFORE_BUILD: pip install pybind11 numpy
    #       CIBW_TEST_REQUIRES: pytest pillow glfw
    #       CIBW_TEST_REQUIRES_LINUX: pytest pillow glfw moderngl
    #       CIBW_TEST_REQUIRES_MACOS: pytest pillow pyopengl
    #       CIBW_TEST_COMMAND: python -m pytest {project}/tests
    #       CIBW_TEST_COMMAND_LINUX: >
    #         xvfb-run -s "-screen 0 640x480x24" python -m pytest {project}/tests
    #       CIBW_REPAIR_WHEEL_COMMAND_LINUX: "auditwheel repair --exclude libEGL.so.1 -w {dest_dir} {wheel}"
    #       CIBW_TEST_SKIP: "*-macosx_arm64"
    # 
    #   - uses: actions/upload-artifact@v7
    #     with:
    #       name: wheel-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.cp }}
    #       path: ./wheelhouse/*.whl
